# Generated by Django 5.0.1 on 2026-02-25 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Level 3', 'Level 3 - Minor crimes (petty theft, small fraud)'), ('Level 2', 'Level 2 - Major crimes (vehicle theft)'), ('Level 1', 'Level 1 - Severe crimes (murder)'), ('Critical', 'Critical - Terrorism, serial murder, assassination')], max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('incident_location', models.TextField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assigned_detective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_assigned_as_detective', to=settings.AUTH_USER_MODEL)),
                ('assigned_sergeant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_assigned_as_sergeant', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'cases',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseComplainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_complainants', to='cases.case')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Complainant',
                'verbose_name_plural': 'Case Complainants',
                'db_table': 'case_complainants',
                'unique_together': {('case', 'complainant')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='complainants',
            field=models.ManyToManyField(related_name='cases_as_complainant', through='cases.CaseComplainant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CaseWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witness_national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('witness_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_witnesses', to='cases.case')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Witness',
                'verbose_name_plural': 'Case Witnesses',
                'db_table': 'case_witnesses',
                'unique_together': {('case', 'witness')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='witnesses',
            field=models.ManyToManyField(related_name='cases_as_witness', through='cases.CaseWitness', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'severity'], name='cases_status_54634f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_date'], name='cases_created_08ebfe_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_detective'], name='cases_assigne_7fe6cb_idx'),
        ),
    ]
