# Generated by Django 5.0.1 on 2026-02-27 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casewitness',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='casewitness',
            name='witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witness_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='casewitness',
            index=models.Index(fields=['case', 'witness_national_id'], name='case_witnes_case_id_d3896c_idx'),
        ),
    ]
