# Generated by Django 5.0.1 on 2026-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_casewitness_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casewitness',
            name='witness_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
