# Generated by Django 5.0.1 on 2026-02-25 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectiveBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_data', models.JSONField(default=dict)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detective_board', to='cases.case')),
                ('detective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detective_boards', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detective Board',
                'verbose_name_plural': 'Detective Boards',
                'db_table': 'detective_boards',
            },
        ),
        migrations.CreateModel(
            name='BoardEvidenceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('related_to', 'Related To'), ('contradicts', 'Contradicts'), ('supports', 'Supports'), ('timeline', 'Timeline'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='evidence.evidence')),
                ('target_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='evidence.evidence')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='detective_board.detectiveboard')),
            ],
            options={
                'verbose_name': 'Board Evidence Connection',
                'verbose_name_plural': 'Board Evidence Connections',
                'db_table': 'board_evidence_connections',
                'unique_together': {('board', 'source_evidence', 'target_evidence')},
            },
        ),
    ]
