# Generated by Django 5.0.1 on 2026-02-25 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Under Investigation', 'Under Investigation'), ('Under Severe Surveillance', 'Under Severe Surveillance'), ('Arrested', 'Arrested'), ('Cleared', 'Cleared')], default='Under Investigation', max_length=30)),
                ('surveillance_start_date', models.DateField(blank=True, null=True)),
                ('arrest_date', models.DateTimeField(blank=True, null=True)),
                ('cleared_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.case')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspect_in_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspect',
                'verbose_name_plural': 'Suspects',
                'db_table': 'suspects',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interrogation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='cases.case')),
                ('interrogator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogations_conducted', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='investigations.suspect')),
            ],
            options={
                'verbose_name': 'Interrogation',
                'verbose_name_plural': 'Interrogations',
                'db_table': 'interrogations',
                'ordering': ['-interrogation_date'],
            },
        ),
        migrations.CreateModel(
            name='GuiltScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Guilt score from 1 to 10')),
                ('justification', models.TextField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guilt_scores_assigned', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guilt_scores', to='cases.case')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guilt_scores', to='investigations.suspect')),
            ],
            options={
                'verbose_name': 'Guilt Score',
                'verbose_name_plural': 'Guilt Scores',
                'db_table': 'guilt_scores',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='CaptainDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('Approve Arrest', 'Approve Arrest'), ('Reject', 'Reject'), ('Request More Evidence', 'Request More Evidence')], max_length=25)),
                ('comments', models.TextField(blank=True)),
                ('requires_chief_approval', models.BooleanField(default=False)),
                ('chief_approval', models.BooleanField(blank=True, null=True)),
                ('chief_approval_date', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_decisions', to='cases.case')),
                ('chief_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_approved_as_chief', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made_as_captain', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_decisions', to='investigations.suspect')),
            ],
            options={
                'verbose_name': 'Captain Decision',
                'verbose_name_plural': 'Captain Decisions',
                'db_table': 'captain_decisions',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['case', 'status'], name='suspects_case_id_76d305_idx'),
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['status'], name='suspects_status_5ef8af_idx'),
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['surveillance_start_date'], name='suspects_surveil_b273a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guiltscore',
            unique_together={('suspect', 'assigned_by')},
        ),
    ]
