# Generated by Django 5.0.1 on 2026-02-25 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_date', models.DateTimeField(blank=True, null=True)),
                ('verdict_date', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('Guilty', 'Guilty'), ('Not Guilty', 'Not Guilty')], max_length=20, null=True)),
                ('punishment_title', models.CharField(blank=True, max_length=200)),
                ('punishment_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='cases.case')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trials_judged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trial',
                'verbose_name_plural': 'Trials',
                'db_table': 'trials',
                'ordering': ['-trial_date'],
            },
        ),
    ]
