# Generated by Django 5.0.1 on 2026-02-25 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_type', models.CharField(choices=[('witness_statement', 'Witness Statement'), ('biological', 'Biological/Medical'), ('vehicle', 'Vehicle'), ('identification', 'Identification Document'), ('other', 'Other')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.TextField(blank=True)),
                ('witness_name', models.CharField(blank=True, max_length=200)),
                ('witness_national_id', models.CharField(blank=True, max_length=50)),
                ('witness_phone', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evidence/witness_statements/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='evidence/witness_statements/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])])),
                ('audio', models.FileField(blank=True, null=True, upload_to='evidence/witness_statements/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a'])])),
                ('evidence_category', models.CharField(blank=True, choices=[('blood', 'Blood'), ('hair', 'Hair'), ('fingerprint', 'Fingerprint'), ('dna', 'DNA'), ('other', 'Other')], max_length=20)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='evidence/biological/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='evidence/biological/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='evidence/biological/images/')),
                ('verified_by_national_id', models.CharField(blank=True, max_length=50)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='cases.case')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_recorded', to=settings.AUTH_USER_MODEL)),
                ('verified_by_forensic_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biological_evidence_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
                'db_table': 'evidence',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['evidence_type'], name='evidence_evidenc_a2d96a_idx'), models.Index(fields=['case', 'evidence_type'], name='evidence_case_id_afc782_idx')],
            },
        ),
    ]
