# Generated by Django 5.0.1 on 2026-02-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='is_valid',
            field=models.BooleanField(blank=True, help_text='True if deemed genuine by Forensic Doctor.', null=True),
        ),
    ]
