# Generated by Django 5.0.1 on 2026-02-25 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('investigations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BailFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('Bail', 'Bail'), ('Fine', 'Fine')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bail_fines', to='cases.case')),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bail_fines_set', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bail_fines', to='investigations.suspect')),
            ],
            options={
                'verbose_name': 'Bail/Fine',
                'verbose_name_plural': 'Bail/Fines',
                'db_table': 'bail_fines',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('gateway_response', models.JSONField(default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('bail_fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.bailfine')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddIndex(
            model_name='bailfine',
            index=models.Index(fields=['status'], name='bail_fines_status_f82c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='bailfine',
            index=models.Index(fields=['due_date'], name='bail_fines_due_dat_29842f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='payment_tra_transac_4a22d3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payment_tra_status_137fde_idx'),
        ),
    ]
