# Generated by Django 5.0.1 on 2026-02-25 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('submission_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Permanently Rejected', 'Permanently Rejected')], default='Pending', max_length=20)),
                ('review_comments', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint', to='cases.case')),
                ('reviewed_by_intern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_reviewed_as_intern', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_reviewed_as_officer', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'db_table': 'complaints',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Returned', 'Returned to Complainant'), ('Forwarded', 'Forwarded to Police Officer'), ('Approved', 'Approved - Case Created'), ('Rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='complaints.complaint')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Review',
                'verbose_name_plural': 'Complaint Reviews',
                'db_table': 'complaint_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaints_status_3d57ee_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['submitted_by'], name='complaints_submitt_0778d7_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_date'], name='complaints_created_01e09c_idx'),
        ),
    ]
