# Generated by Django 5.0.1 on 2026-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Returned', 'Returned (Requires Modification)'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Permanently Rejected', 'Permanently Rejected')], default='Pending', max_length=20),
        ),
    ]
